services:
  api:
    container_name: coffeeshop-react
    build:
      context: ../.
      dockerfile: ./Dockerfile
    env_file: "../.env"
    ports: 
      - 3000:3000
    develop:
      watch:
        - path: .
          action: rebuild